const provaaluno = [
  [
    { number: "1", letter: "C" },
    { number: "2", letter: "B" },
    { number: "3", letter: "C" },
    { number: "4", letter: "A" },
    { number: "5", letter: "B" },
    { number: "6", letter: "D" },
    { number: "7", letter: "A" },
    { number: "8", letter: "D" },
    { number: "9", letter: "C" },
    { number: "10", letter: "D" },
    { number: "11", letter: "A" },
    { number: "12", letter: "B" },
    { number: "13", letter: "D" },
    { number: "14", letter: "C" },
    { number: "15", letter: "C" },
    { number: "16", letter: "B" },
    { number: "17", letter: "A" },
    { number: "18", letter: "D" },
    { number: "19", letter: "B" },
    { number: "20", letter: "A" },
    { number: "21", letter: "A" },
    { number: "22", letter: "C" },
    { number: "23", letter: "B" },
    { number: "24", letter: "B" },
    { number: "25", letter: "A" },
    { number: "26", letter: "D" },
    { number: "27", letter: "D" },
    { number: "28", letter: "C" },
    { number: "29", letter: "D" },
    { number: "30", letter: "C" },
  ],
  [
    { number: "31", letter: "X" },
    { number: "32", letter: "X" },
    { number: "33", letter: "X" },
    { number: "34", letter: "X" },
    { number: "35", letter: "X" },
    { number: "36", letter: "X" },
    { number: "37", letter: "X" },
    { number: "38", letter: "X" },
    { number: "39", letter: "X" },
    { number: "40", letter: "X" },
    { number: "41", letter: "X" },
    { number: "42", letter: "X" },
    { number: "43", letter: "X" },
    { number: "44", letter: "X" },
    { number: "45", letter: "X" },
    { number: "46", letter: "X" },
    { number: "47", letter: "X" },
    { number: "48", letter: "X" },
    { number: "49", letter: "X" },
    { number: "50", letter: "X" },
    { number: "51", letter: "X" },
    { number: "52", letter: "X" },
    { number: "53", letter: "X" },
    { number: "54", letter: "X" },
    { number: "55", letter: "X" },
    { number: "56", letter: "X" },
    { number: "57", letter: "X" },
    { number: "58", letter: "X" },
    { number: "59", letter: "X" },
    { number: "60", letter: "X" },
  ],
  [
    { number: "1", letter: "X" },
    { number: "2", letter: "X" },
    { number: "3", letter: "X" },
    { number: "4", letter: "X" },
    { number: "5", letter: "X" },
    { number: "6", letter: "X" },
    { number: "7", letter: "X" },
    { number: "8", letter: "X" },
    { number: "9", letter: "X" },
    { number: "10", letter: "X" },
    { number: "11", letter: "X" },
    { number: "12", letter: "X" },
    { number: "13", letter: "X" },
    { number: "14", letter: "X" },
    { number: "15", letter: "X" },
    { number: "16", letter: "X" },
    { number: "17", letter: "X" },
    { number: "18", letter: "X" },
    { number: "19", letter: "X" },
    { number: "20", letter: "X" },
    { number: "21", letter: "X" },
    { number: "22", letter: "X" },
    { number: "23", letter: "X" },
    { number: "24", letter: "X" },
    { number: "25", letter: "X" },
    { number: "26", letter: "X" },
    { number: "27", letter: "X" },
    { number: "28", letter: "X" },
    { number: "29", letter: "X" },
    { number: "30", letter: "X" },
  ],
  [
    { number: "31", letter: "X" },
    { number: "32", letter: "X" },
    { number: "33", letter: "X" },
    { number: "34", letter: "X" },
    { number: "35", letter: "X" },
    { number: "36", letter: "X" },
    { number: "37", letter: "X" },
    { number: "38", letter: "X" },
    { number: "39", letter: "X" },
    { number: "40", letter: "X" },
    { number: "41", letter: "X" },
    { number: "42", letter: "X" },
    { number: "43", letter: "X" },
    { number: "44", letter: "X" },
    { number: "45", letter: "X" },
    { number: "46", letter: "X" },
    { number: "47", letter: "X" },
    { number: "48", letter: "X" },
    { number: "49", letter: "X" },
    { number: "50", letter: "X" },
    { number: "51", letter: "X" },
    { number: "52", letter: "X" },
    { number: "53", letter: "X" },
    { number: "54", letter: "X" },
    { number: "55", letter: "X" },
    { number: "56", letter: "X" },
    { number: "57", letter: "X" },
    { number: "58", letter: "X" },
    { number: "59", letter: "X" },
    { number: "60", letter: "X" },
  ],
];

const gabarito = [
  [
    { number: "1", letter: "C" },
    { number: "2", letter: "B" },
    { number: "3", letter: "C" },
    { number: "4", letter: "A" },
    { number: "5", letter: "B" },
    { number: "6", letter: "D" },
    { number: "7", letter: "A" },
    { number: "8", letter: "D" },
    { number: "9", letter: "C" },
    { number: "10", letter: "D" },
    { number: "11", letter: "A" },
    { number: "12", letter: "B" },
    { number: "13", letter: "D" },
    { number: "14", letter: "C" },
    { number: "15", letter: "C" },
    { number: "16", letter: "B" },
    { number: "17", letter: "A" },
    { number: "18", letter: "D" },
    { number: "19", letter: "B" },
    { number: "20", letter: "A" },
    { number: "21", letter: "A" },
    { number: "22", letter: "C" },
    { number: "23", letter: "B" },
    { number: "24", letter: "B" },
    { number: "25", letter: "A" },
    { number: "26", letter: "D" },
    { number: "27", letter: "D" },
    { number: "28", letter: "C" },
    { number: "29", letter: "D" },
    { number: "30", letter: "C" },
  ],
  [
    { number: "31", letter: "C" },
    { number: "32", letter: "D" },
    { number: "33", letter: "A" },
    { number: "34", letter: "D" },
    { number: "35", letter: "D" },
    { number: "36", letter: "A" },
    { number: "37", letter: "D" },
    { number: "38", letter: "C" },
    { number: "39", letter: "D" },
    { number: "40", letter: "C" },
    { number: "41", letter: "B" },
    { number: "42", letter: "D" },
    { number: "43", letter: "C" },
    { number: "44", letter: "A" },
    { number: "45", letter: "A" },
    { number: "46", letter: "D" },
    { number: "47", letter: "B" },
    { number: "48", letter: "C" },
    { number: "49", letter: "A" },
    { number: "50", letter: "A" },
    { number: "51", letter: "B" },
    { number: "52", letter: "B" },
    { number: "53", letter: "B" },
    { number: "54", letter: "C" },
    { number: "55", letter: "A" },
    { number: "56", letter: "B" },
    { number: "57", letter: "B" },
    { number: "58", letter: "B" },
    { number: "59", letter: "C" },
    { number: "60", letter: "C" },
  ],
  [
    { number: "1", letter: "D" },
    { number: "2", letter: "D" },
    { number: "3", letter: "A" },
    { number: "4", letter: "B" },
    { number: "5", letter: "A" },
    { number: "6", letter: "C" },
    { number: "7", letter: "C" },
    { number: "8", letter: "A" },
    { number: "9", letter: "A" },
    { number: "10", letter: "B" },
    { number: "11", letter: "C" },
    { number: "12", letter: "A" },
    { number: "13", letter: "B" },
    { number: "14", letter: "C" },
    { number: "15", letter: "A" },
    { number: "16", letter: "D" },
    { number: "17", letter: "A" },
    { number: "18", letter: "C" },
    { number: "19", letter: "B" },
    { number: "20", letter: "D" },
    { number: "21", letter: "A" },
    { number: "22", letter: "B" },
    { number: "23", letter: "D" },
    { number: "24", letter: "A" },
    { number: "25", letter: "D" },
    { number: "26", letter: "C" },
    { number: "27", letter: "A" },
    { number: "28", letter: "D" },
    { number: "29", letter: "A" },
    { number: "30", letter: "D" },
  ],
  [
    { number: "31", letter: "C" },
    { number: "32", letter: "C" },
    { number: "33", letter: "C" },
    { number: "34", letter: "D" },
    { number: "35", letter: "D" },
    { number: "36", letter: "A" },
    { number: "37", letter: "C" },
    { number: "38", letter: "D" },
    { number: "39", letter: "B" },
    { number: "40", letter: "C" },
    { number: "41", letter: "D" },
    { number: "42", letter: "B" },
    { number: "43", letter: "A" },
    { number: "44", letter: "A" },
    { number: "45", letter: "A" },
    { number: "46", letter: "C" },
    { number: "47", letter: "D" },
    { number: "48", letter: "B" },
    { number: "49", letter: "B" },
    { number: "50", letter: "D" },
    { number: "51", letter: "C" },
    { number: "52", letter: "D" },
    { number: "53", letter: "A" },
    { number: "54", letter: "C" },
    { number: "55", letter: "A" },
    { number: "56", letter: "B" },
    { number: "57", letter: "D" },
    { number: "58", letter: "D" },
    { number: "59", letter: "D" },
    { number: "60", letter: "B" },
  ],
];

const CalculatingFinalExam = (gabarito, respostas, yaer) => {
  const materias = [
    {
      id: 1,
      name: "Ciências da Natureza e suas Tecnologias",
      color: "#cf86e6",
      acertos: [],
      erros: [],
    },
    {
      id: 2,
      name: "Matemática e suas Tecnologias",
      color: "#e6e686",
      acertos: [],
      erros: [],
    },
    {
      id: 3,
      name: "Linguagens, Códigos e suas Tecnologias",
      color: "#86cee6",
      acertos: [],
      erros: [],
    },
    {
      id: 4,
      name: "Ciências Humanas e suas Tecnologias",
      color: "#86e6a0",
      acertos: [],
      erros: [],
    },
    {
      acertostotais: 0,
      errostotais: 0,
      aprovadas: [],
      reprovadas: [],
      nãoaplicadas: [],
    },
  ];

  const UserAnswers = respostas;

  const gabaritoprova = gabarito;

  if (gabaritoprova.length > 0 && UserAnswers.length > 0) {
    for (let i = 0; i < gabaritoprova.length; i++) {
      for (let j = 0; j < gabaritoprova[i].length; j++) {
        if (gabaritoprova[i][j].letter === UserAnswers[i][j].letter) {
          materias[i].acertos.push(UserAnswers[i][j]);
        } else {
          materias[i].erros.push(UserAnswers[i][j]);
        }
      }
    }
  }

  if (materias !== undefined) {
    for (let i = 0; i < 4; i++) {
      materias[4].acertostotais += materias[i].acertos.length;
      materias[4].errostotais += materias[i].erros.length;

      if (materias[i].erros === "X") {
        materias[4].nãoaplicadas.push(materias[i].name);
      }
      if (materias[i].acertos.length > 15) {
        materias[4].aprovadas.push(materias[i].name);
      } else {
        materias[4].reprovadas.push(materias[i].name);
      }
    }
  }

  return materias;
};

console.log(CalculatingFinalExam(gabarito, provaaluno)[4]);
